name: Docker Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          cd docker && docker build . -f ./Dockerfile.x86 -t ghcr.io/${{ github.repository }}:latest

